- debug:
    msg: "Role execution being skipped as it has run already."
  when: cluster_single_node_role_already_ran is defined and cluster_single_node_role_already_ran

- include: run.yml
  when: cluster_single_node_role_already_ran is undefined and not cluster_single_node_role_already_ran
